name: Publish

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build_x64:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish
        run: |
          docker build -t github-actions-runner .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-x64
          docker push coderookieerick/github-actions-runner:linux-x64

  build_arm64:
    runs-on: MACROARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish
        run: |
          docker build -t github-actions-runner .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-arm64
          docker push coderookieerick/github-actions-runner:linux-arm64