name: Build and publish container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: dockerable
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker build -t github-actions-runner .
          docker tag github-actions-runner coderookieerick/github-actions-runner
          docker push coderookieerick/github-actions-runner:latest