name: Publish

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish linux-x64
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=x64" .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-x64
          docker push coderookieerick/github-actions-runner:linux-x64

      - name: Publish linux-arm64
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=arm64" .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-arm64
          docker push coderookieerick/github-actions-runner:linux-arm64