name: Publish

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build linux-x64
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=x64" .

      - name: Build linux-arm64
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=arm64" .

  publish-linux-x64:
    runs-on: ubuntu-01
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=x64" .

      - name: Publish
        run: |
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-x64
          docker push coderookieerick/github-actions-runner:linux-x64

  publish-linux-arm64:
    runs-on: ARM64
    needs: [ build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=arm64" .

      - name: Publish
        run: |
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-arm64
          docker push coderookieerick/github-actions-runner:linux-arm64