name: Publish

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: MACROARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish
        run: |
          docker build -f ./gar.base.dockerfile -t github-actions-runner .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:linux-arm64
          docker push coderookieerick/github-actions-runner:linux-arm64

  build_version:
    runs-on: MACROARM64
    strategy:
      matrix:
        version: [dotnet, node]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish
        run: |
          docker build -f ./gar.${{ matrix.version }}.dockerfile -t github-actions-runner: .
          docker login -u coderookieerick -p ${{ secrets.ACTIONS_RUNNER_DOCKER_IMAGE_TOKEN }}
          docker tag github-actions-runner coderookieerick/github-actions-runner:${{ matrix.version }}-linux-arm64
          docker push coderookieerick/github-actions-runner:${{ matrix.version }}-linux-arm64