name: Test

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: dockerable
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker build -t github-actions-runner .