name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_x64:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Base
        run: |
          docker build -f ./gar.base.dockerfile -t github-actions-runner .

      - name: Test Dotnet8
        run: |
          docker build -f ./gar.dotnet8.dockerfile -t github-actions-runner .

      - name: Test Python3
        run: |
          docker build -f ./gar.python3.dockerfile -t github-actions-runner .

  test_arm64:
    runs-on: MACROARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Base
        run: |
          docker build -f ./gar.base.dockerfile -t github-actions-runner .

      - name: Test Dotnet8
        run: |
          docker build -f ./gar.dotnet8.dockerfile -t github-actions-runner .

      - name: Test Python3
        run: |
          docker build -f ./gar.python3.dockerfile -t github-actions-runner .