name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_x64:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=x64" .

  test_arm64:
    runs-on: ARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test
        run: |
          docker build -t github-actions-runner --build-arg="OS=linux" --build-arg="ARCH=arm64" .