name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_x64:
    strategy:
      matrix: 
        version: [base, node, dotnet]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test ${{matrix.version}}
        run: |
          docker build -f ./gar.${{matrix.version}}.dockerfile -t github-actions-runner .

  test_arm64:
    runs-on: MACROARM64
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test ${{matrix.version}}
        run: |
          docker build -f ./gar.${{matrix.version}}.dockerfile -t github-actions-runner .